// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"rest-api-app/src/database"
	"rest-api-app/src/domain/video"
)

// Injectors from wire.go:

func initVideoController() video.VideoController {
	db := database.GetDB()
	videoRepository := video.ProvideVideoRepository(db)
	videoService := video.ProvideVideoService(videoRepository)
	videoController := video.ProvideVideoController(videoService)
	return videoController
}
